#include "foo.h"
#include "toolbox.h"

int main() {
    REG_SOUNDCNT_X = SOUNDCNT_X_CHANNEL1_ON | SOUNDCNT_X_MASTER_ON;
    REG_SOUNDCNT_L = SOUNDCNT_L_RIGHT_VOLUME(7) | SOUNDCNT_L_LEFT_VOLUME(7) |SOUNDCNT_L_RIGHT_CHANNEL1_ENABLE | SOUNDCNT_L_LEFT_CHANNEL1_ENABLE;
    REG_SOUNDCNT_H = SOUNDCNT_H_VOL100;
    REG_SOUND1CNT_H = 0xF200;
    REG_SOUND1CNT_X = 0x83FF;
    while(1);
    return 0;
}